[project]
name = "promptbind"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dataclasses>=0.8",
    "jinja2>=3.1.6",
    "toml>=0.10.2",
]
